In [1]:
import numpy as np

In [2]:
# Create array by passing in list of list
ratings = np.array([[94,89,63], [93,92,48], [92,94,56]])

ratings

array([[94, 89, 63],
       [93, 92, 48],
       [92, 94, 56]])

In [15]:
d = np.append(ratings, [[92, 88, 78]], axis=0)
ratings

array([[94, 89, 63],
       [93, 92, 48],
       [92, 94, 56]])

In [10]:
ratings.shape

(3, 3)

In [14]:
ratings

array([[94, 89, 63],
       [93, 92, 48],
       [92, 94, 56]])

In [16]:
d

array([[94, 89, 63],
       [93, 92, 48],
       [92, 94, 56],
       [92, 88, 78]])

In [7]:
ratings[:3:]

array([[94, 89, 63],
       [93, 92, 48],
       [92, 94, 56]])

In [8]:
ratings[:1:]

array([[94, 89, 63]])

In [10]:
ratings.shape

(3, 3)

In [13]:
np.ones((13,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
ratings[0,0]

94

In [15]:
ratings[:,0]

array([94, 93, 92])

In [16]:
ratings

array([[94, 89, 63],
       [93, 92, 48],
       [92, 94, 56]])

In [17]:
ratings[:,1]

array([89, 92, 94])

In [18]:
ratings[:,:]

array([[94, 89, 63],
       [93, 92, 48],
       [92, 94, 56]])

In [19]:
ratings[:]

array([[94, 89, 63],
       [93, 92, 48],
       [92, 94, 56]])

In [20]:
ratings[::-1]

array([[92, 94, 56],
       [93, 92, 48],
       [94, 89, 63]])

In [21]:
ratings[-1,:]

array([92, 94, 56])

In [22]:
ratings

array([[94, 89, 63],
       [93, 92, 48],
       [92, 94, 56]])

In [28]:
ratings[ratings > 90]

array([94, 93, 92, 92, 94])

In [29]:
x = np.array([[4,5,0], [3,2,5], [6,6,7]])

In [30]:
x

array([[4, 5, 0],
       [3, 2, 5],
       [6, 6, 7]])

In [32]:
x[:,1]

array([5, 2, 6])

In [35]:
x[1:3,1:3]

array([[2, 5],
       [6, 7]])

In [36]:
x[x > 5]

array([6, 6, 7])

In [37]:
x.sum(axis=0)

array([13, 13, 12])

In [17]:
import pandas as pd
 
df = pd.DataFrame({'Age': [30, 20, 22, 40, 32, 28, 39],
                   'Color': ['Blue', 'Green', 'Red', 'White', 'Gray', 'Black',
                             'Red'],
                   'Food': ['Steak', 'Lamb', 'Mango', 'Apple', 'Cheese',
                            'Melon', 'Beans'],
                   'Height': [165, 70, 120, 80, 180, 172, 150],
                   'Score': [4.6, 8.3, 9.0, 3.3, 1.8, 9.5, 2.2],
                   'State': ['NY', 'TX', 'FL', 'AL', 'AK', 'TX', 'TX']
                   },
                  index=['Jane', 'Nick', 'Aaron', 'Penelope', 'Dean',
                         'Christina', 'Cornelia'])

df

Age  Color    Food  Height  Score State
Jane        30   Blue   Steak     165    4.6    NY
Nick        20  Green    Lamb      70    8.3    TX
Aaron       22    Red   Mango     120    9.0    FL
Penelope    40  White   Apple      80    3.3    AL
Dean        32   Gray  Cheese     180    1.8    AK
Christina   28  Black   Melon     172    9.5    TX
Cornelia    39    Red   Beans     150    2.2    TX

In [19]:
df.iloc[4]

Age           32
Color       Gray
Food      Cheese
Height       180
Score        1.8
State         AK
Name: Dean, dtype: object

In [23]:
df.sort_values

<bound method DataFrame.sort_values of            Age  Color    Food  Height  Score State
Jane        30   Blue   Steak     165    4.6    NY
Nick        20  Green    Lamb      70    8.3    TX
Aaron       22    Red   Mango     120    9.0    FL
Penelope    40  White   Apple      80    3.3    AL
Dean        32   Gray  Cheese     180    1.8    AK
Christina   28  Black   Melon     172    9.5    TX
Cornelia    39    Red   Beans     150    2.2    TX>

In [25]:
df.sort()

AttributeError: 'DataFrame' object has no attribute 'sort'

In [26]:
df

Age  Color    Food  Height  Score State
Jane        30   Blue   Steak     165    4.6    NY
Nick        20  Green    Lamb      70    8.3    TX
Aaron       22    Red   Mango     120    9.0    FL
Penelope    40  White   Apple      80    3.3    AL
Dean        32   Gray  Cheese     180    1.8    AK
Christina   28  Black   Melon     172    9.5    TX
Cornelia    39    Red   Beans     150    2.2    TX

In [29]:
df[(df['Age'] > 25) & (df['State'] == 'TX')]

Age  Color   Food  Height  Score State
Christina   28  Black  Melon     172    9.5    TX
Cornelia    39    Red  Beans     150    2.2    TX

In [38]:
df['decades'] = df['Age'].apply(lambda x: x / 10)
df

Age  Color    Food  Height  Score State  decades
Jane        30   Blue   Steak     165    4.6    NY      3.0
Nick        20  Green    Lamb      70    8.3    TX      2.0
Aaron       22    Red   Mango     120    9.0    FL      2.2
Penelope    40  White   Apple      80    3.3    AL      4.0
Dean        32   Gray  Cheese     180    1.8    AK      3.2
Christina   28  Black   Melon     172    9.5    TX      2.8
Cornelia    39    Red   Beans     150    2.2    TX      3.9

In [37]:
df['decades'] = df.applymap(lambda x: x / 10)

TypeError: ("unsupported operand type(s) for /: 'str' and 'int'", 'occurred at index Color')